"""add discount_percent to products

Revision ID: 555934651fed
Revises: 3e8083510eda
Create Date: 2026-07-15 22:15:00.123953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555934651fed'
down_revision: Union[str, Sequence[str], None] = '3e8083510eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_percent')
    # ### end Alembic commands ###
