"""add delivery_address to orders

Revision ID: 49cebe9c609a
Revises: e146d7c4a6a1
Create Date: 2026-07-17 00:15:41.814666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49cebe9c609a'
down_revision: Union[str, Sequence[str], None] = 'e146d7c4a6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_address')
    # ### end Alembic commands ###
