"""add role to users

Revision ID: 610b1c3c518b
Revises: f65db1257dcb
Create Date: 2026-08-03 20:26:31.422352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610b1c3c518b'
down_revision: Union[str, Sequence[str], None] = 'f65db1257dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.Enum('admin', 'manager', 'customer', name='userrole'),
            nullable=False,
            server_default='customer',
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
